site_name: My Wiki


nav:
  - Gnatt Chart(s): 
    - GnattChart 1: Gnatt-Chart.md
    - GnattChart 2: Gnatt-Chart(2).md
  - Proposal: Proposal.md
  - Week 1:
      - Proposal: Proposal.md
  - Week 2:
      - Status Report: status-reports/status-report1.md
  - Week 3: 
      - Status Report: status-reports/status-report2.md
      - Use Cases: usecase.md
  - Week 4:
      - Status Report: status-reports/status-report3.md 
      - Figma: 'https://www.figma.com/design/Xo5ZwGZhR0lMjVoGqHKCcr/CarbonRoughFigma?node-id=0-1&t=rj1thUGQ5IFmG4RJ-1'
  - Week 5:
      - Status Report: status-reports/status-report4.md
      - ERD: erd.md 
      - Midterm Presentation: MidtermPPTX.md
  - Week 6:
      - Status Report: status-reports/status-report5.md
      - Activity Diagram: activity-diagram.md
  - Week 7:
      - Status Report: status-reports/status-report6.md
      - Class Diagram: class-diagram.md
  - Week 8:
      - Status Report: status-reports/status-report7.md
      - Heuristic Evaluation: HE.md
  - Week 9:
      - Status Report: status-reports/status-report8.md
      - Final Gnatt Chart: Gnatt-Chart.md
  - Semester 2 :
      - W2 Status Report: status-reports/s2-status-report2.md
      - W3 Status Report: status-reports/s2-status-report3.md
      - W4 Status Report: status-reports/s2-status-report4.md
      - W5 Status Report: status-reports/s2-status-report5.md
      - W6 Status Report: status-reports/s2-status-report6.md
      - W7 Status Report: status-reports/s2-status-report7.md
      - W8 Status Report: status-reports/s2-status-report8.md
      - W9 Status Report: status-reports/s2-status-report9.md
      - Gnatt Chart P2: Gnatt-Chart(2).md
      - Final Presentation: FinalPresentationS2.md
      - Tech Spec Document: TechSpec.md